import { useState, useEffect } from "react";
import axios from "axios";
import TrackCard from "./TrackCard";

export default function Tracks({ trackshref }) {
  const [tracks, setTracks] = useState([]);
  const [valence, setValence] = useState(50);
  const [danceability, setDanceability] = useState(50);
  const [energy, setEnergy] = useState(50);
  const [submitted, setSubmitted] = useState(false);
  const [hover, setHover] = useState(false);

  const accessToken = localStorage.getItem("accessToken");

  const song = {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9",
          },
          href: "https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9",
          id: "3Isy6kedDrgPYoTS1dazA9",
          name: "Sean Paul",
          type: "artist",
          uri: "spotify:artist:3Isy6kedDrgPYoTS1dazA9",
        },
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/5xrOcCoO3jkXRjHQjfESM6",
      },
      href: "https://api.spotify.com/v1/albums/5xrOcCoO3jkXRjHQjfESM6",
      id: "5xrOcCoO3jkXRjHQjfESM6",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b2732d564195ed3dd7b70d64862c",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e022d564195ed3dd7b70d64862c",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d000048512d564195ed3dd7b70d64862c",
          width: 64,
        },
      ],
      name: "Mad Love The Prequel",
      release_date: "2018-06-29",
      release_date_precision: "day",
      total_tracks: 9,
      type: "album",
      uri: "spotify:album:5xrOcCoO3jkXRjHQjfESM6",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9",
        },
        href: "https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9",
        id: "3Isy6kedDrgPYoTS1dazA9",
        name: "Sean Paul",
        type: "artist",
        uri: "spotify:artist:3Isy6kedDrgPYoTS1dazA9",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we",
        },
        href: "https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we",
        id: "6M2wZ9GZgrQXHCFfjv46we",
        name: "Dua Lipa",
        type: "artist",
        uri: "spotify:artist:6M2wZ9GZgrQXHCFfjv46we",
      },
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK",
    ],
    disc_number: 1,
    duration_ms: 221176,
    explicit: false,
    external_ids: {
      isrc: "GBUM71604557",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/48QmG1dfvMuYLxMPt7KSRA",
    },
    href: "https://api.spotify.com/v1/tracks/48QmG1dfvMuYLxMPt7KSRA",
    id: "48QmG1dfvMuYLxMPt7KSRA",
    is_local: false,
    name: "No Lie",
    popularity: 83,
    preview_url: null,
    track_number: 9,
    type: "track",
    uri: "spotify:track:48QmG1dfvMuYLxMPt7KSRA",
  };

  useEffect(() => {
    axios
      .get(trackshref, { headers: { Authorization: `Bearer ${accessToken}` } })
      .then((response) => {
        setTracks(response.data.items);
      })
      .catch((error) => {
        console.log("Stupid error ", error);
      });
  }, [trackshref]);

  const handleClick = () => {
    setSubmitted(!submitted);
  };

  if (!submitted) {
    return (
      <div>
        <div className="sliders">
          <h3>Valence</h3>
          <div>{valence}</div>
          <input
            type="range"
            min="1"
            max="100"
            value={valence}
            onChange={(e) => setValence(e.target.value)}
          ></input>
        </div>
        <div className="sliders">
          <h3>Danceability</h3>
          <div>{danceability}</div>
          <input
            type="range"
            min="1"
            max="100"
            value={danceability}
            onChange={(e) => setDanceability(e.target.value)}
          ></input>
        </div>
        <div className="sliders">
          <h3>Energy</h3>
          <div>{energy}</div>
          <input
            type="range"
            min="1"
            max="100"
            value={energy}
            onChange={(e) => setEnergy(e.target.value)}
          ></input>
        </div>
        <button onClick={handleClick}> Make Playlist </button>
      </div>
    );
  }
  return (
    <TrackCard song={song} />
  );
}
